name: Docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Adds terraform docs to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ./
          config-file: ./docs/.terraform-docs.yml
          git-push: "true"
